title: Lois Randolph
description: Welcome to my portfolio! I also have articles on different bioinformatics/data science topics ðŸ¤“
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
markdown: kramdown

kramdown:
  input: GFM
