title: "Lois Randolph Portfolio"
description: "My portfolio site"
baseurl: ""  # leave empty if your repo is user.github.io
url: "https://low-is.github.io"

theme: minima   # GitHub-supported theme
plugins:
  - jekyll-feed
