title: "Lois Randolph Portfolio"
description: "Bioinformatics & Data Science Portfolio"
baseurl: "/Lois_portfolio"   # important, matches your repo name
url: "https://low-is.github.io"
theme: architect            # if using a theme
